jobs:
  release:
    docker:
      - image: node:11
    steps:
      - checkout
      - run: npm i -g semantic-release@15
      - run: semantic-release
workflows:
  version: 2
  test-and-build:
    jobs:
      - release:
          filters:
            branches:
              only: master
